import 'package:flutter/material.dart';
import '../models/mishnah.dart';
import '../services/app_state.dart';
class OnboardingScreen extends StatefulWidget{final AppState state;const OnboardingScreen({super.key,required this.state});@override State<OnboardingScreen> createState()=>_OnboardingScreenState();}
class _OnboardingScreenState extends State<OnboardingScreen>{int step=0;final ids=<String>{};DateTime target=DateTime.now().add(const Duration(days:90));final per=TextEditingController(text:'3');
@override Widget build(BuildContext c){final d=widget.state.data!;return Scaffold(appBar:AppBar(title:Text(step==0?'בחירת מסכתות':step==1?'תאריך יעד':'קצב לימוד')),body:Directionality(textDirection:TextDirection.rtl,child:Column(children:[Expanded(child:step==0?_tree(d):step==1?_date(c):_pace(c)),Padding(padding:const EdgeInsets.all(16),child:Row(children:[if(step>0)Expanded(child:OutlinedButton(onPressed:()=>setState(()=>step--),child:const Text('חזרה'))),if(step>0)const SizedBox(width:10),Expanded(child:FilledButton(onPressed:_next,child:Text(step==2?'סיום':'המשך')))]))]));}
Widget _tree(MishnahData d)=>ListView(children:[for(final s in d.sedarim)ExpansionTile(title:Text(s.name,style:const TextStyle(fontWeight:FontWeight.bold)),leading:Checkbox(value:s.tractates.every((t)=>ids.contains(t.id)),onChanged:(v)=>setState((){for(final t in s.tractates){v==true?ids.add(t.id):ids.remove(t.id);}}),),children:[for(final t in s.tractates)CheckboxListTile(value:ids.contains(t.id),onChanged:(v)=>setState(()=>v==true?ids.add(t.id):ids.remove(t.id)),title:Text(t.name),subtitle:Text('${t.chapters} פרקים'))])]);
Widget _date(BuildContext c)=>Center(child:Column(mainAxisSize:MainAxisSize.min,children:[const Text('בחר תאריך יעד לסיום'),const SizedBox(height:12),FilledButton.icon(onPressed:()async{final x=await showDatePicker(context:c,firstDate:DateTime.now(),lastDate:DateTime.now().add(const Duration(days:3650)),initialDate:target);if(x!=null)setState(()=>target=x);},icon:const Icon(Icons.calendar_month),label:Text('${target.day}/${target.month}/${target.year}'))]));
Widget _pace(BuildContext c){final total=ids.fold(0,(sum,id)=>sum+widget.state.data!.tractate(id).chapters);final n=int.tryParse(per.text)??0;final days=target.difference(DateTime.now()).inDays+1;final req=days<=0?total:(total+days-1)~/days;final finishDays=n<=0?0:(total+n-1)~/n;final finish=DateTime.now().add(Duration(days:finishDays==0?0:finishDays-1));return Padding(padding:const EdgeInsets.all(20),child:Column(children:[Text('סה"כ $total פרקים נבחרו'),TextField(controller:per,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'כמה פרקים ביום?',border:OutlineInputBorder()),onChanged:(_)=>setState((){})),const SizedBox(height:20),Text(n>=req?'בקצב של $n פרקים ביום, תסיים בתאריך ${finish.day}/${finish.month}/${finish.year}':'כדי לסיים בתאריך היעד, עליך ללמוד $req פרקים ביום',textAlign:TextAlign.center,style:Theme.of(c).textTheme.titleMedium)]));}
void _next(){if(step==0&&ids.isEmpty){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('יש לבחור לפחות מסכת אחת')));return;}if(step<2){setState(()=>step++);}else{final n=int.tryParse(per.text)??1;widget.state.finishOnboarding(ids:ids,targetDate:target,perDay:n.clamp(1,999));}}
}